server:
  address: 0.0.0.0
  port: 8082

# 数据库数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.22.185.20:3306/robot?useSSL=false&serverTimezone=UTC
    username: chruen
    password: 12345678
  data:
    redis:
      host: 172.22.185.20
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      password: 12345678




logging:
  file:
    name: log/log.log
  level:
    root: info
    com.swjtu.robot.masterserver: debug

